In [4]:
from PIL import Image

image = Image.open('../data/dest_images/kakao2.jpeg')
# <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=600x450 at 0x7F086E0DB280>

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=600x450 at 0x7F034C382AC0>


In [5]:
image = image.convert("RGB")

In [6]:
print(image)


<PIL.Image.Image image mode=RGB size=600x450 at 0x7F034C370F70>


In [13]:
from facenet_pytorch import MTCNN 
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

net = MTCNN(keep_all=True)
image = image
bboxes, probs = net.detect(image)
print(bboxes)

[[-35.86761  211.94933   82.33974  356.8034  ]
 [232.58357  132.47911  286.23203  208.59709 ]
 [529.3781    91.53727  569.26263  140.48383 ]
 [470.79102  125.240135 508.9288   173.52531 ]
 [262.56848   75.16538  294.36047  116.921104]
 [398.42337  124.349556 431.39294  162.16096 ]
 [  4.185173  87.63054   36.258656 123.131645]
 [135.95163  118.55747  165.89163  154.7335  ]
 [ 44.917484  95.21224   69.773834 124.76916 ]
 [470.86578   95.01359  493.51846  124.547554]
 [352.95364  101.220215 370.09363  124.29632 ]
 [233.431     90.328384 251.61328  112.07997 ]
 [512.38      96.5832   529.6317   117.98675 ]]
